services:
  postgres:
    image: postgres:16
    container_name: Grabbit_postgres
    restart: always
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: passworddev
      POSTGRES_DB: Grabbit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

   
  adminer:
    image: adminer
    container_name: notes_adminer
    restart: always
    ports:
      - "8080:8080"   

volumes:
  pgdata: